require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - db/**/*
    - config/**/*
    - node_modules/**/*
    - bin/*
    - vendor/**/*
  TargetRubyVersion: 3.1

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

RSpec/ImplicitExpect:
  EnforcedStyle: should

RSpec/MultipleExpectations:
  Max: 2

RSpec/Capybara/FeatureMethods:
  EnabledMethods:
    - feature
    - scenario
    - given
    - given!
    - background
